services:
  postgres:
    image: postgres
    container_name: postgres
    depends_on:
      overhang-backend-config:
        condition: service_healthy
      overhang-backend-registry:
        condition: service_healthy
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/
    networks:
      - overhang-network

  overhang-backend-gateway:
    build:
      context: ../overhang-backend-gateway
      dockerfile: Dockerfile
      args:
        SKIP_TESTS: true
    container_name: overhang-backend-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=http://overhang-backend-config:8888/
    depends_on:
      overhang-backend-config:
        condition: service_healthy
      overhang-backend-registry:
        condition: service_healthy
      overhang-backend-auth:
        condition: service_healthy
        restart: true
    networks:
      - overhang-network

  overhang-backend-auth:
    build:
      context: ../overhang-backend-auth
      dockerfile: Dockerfile
      args:
        SKIP_TESTS: true
    container_name: overhang-backend-auth
    expose:
      - "8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=http://overhang-backend-config:8888/
      - JWT_EXPIRATION=86400000 # 1 day
      - JWT_SECRET=0c39f331f68026adb5226e297264f4818490350fbb72b5ac6a7d36d75ef75943 # Dummy secret
    depends_on:
      overhang-backend-config:
        condition: service_healthy
        restart: true
      overhang-backend-registry:
        condition: service_healthy
        restart: true
      postgres:
        condition: service_started
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-sS", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - overhang-network

  overhang-backend-registry:
    build:
      context: ../overhang-backend-registry
      dockerfile: Dockerfile
      args:
        SKIP_TESTS: true
    container_name: overhang-backend-registry
    expose:
      - "8761"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=http://overhang-backend-config:8888/
    healthcheck:
      test: ["CMD", "curl", "-sS", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      overhang-backend-config:
        condition: service_healthy
        restart: true
    networks:
      - overhang-network

  overhang-backend-config:
    build:
      context: ../overhang-backend-config
      dockerfile: Dockerfile
    container_name: overhang-backend-config
    expose:
      - "8888"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    healthcheck:
      test: ["CMD", "curl", "-sS", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - overhang-network

networks:
  overhang-network:
    driver: bridge
